baseURL = "http://techblog.on-going.jp/"
languageCode = "jp"
theme = "anatole"
hasCJKLanguage = true



[params]
title = "on-going's Tech Blog"
author = "techblog.on-going."
profilePicture = "images/profile.jpg"



## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "mathjax"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/izewfktvy533zjmn"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/izewfktvy"

[[params.socialIcons]]
icon = "fa-facebook"
title = "Facebook"
url = "https://www.facebook.com/profile.php?id=100023692920069"

[[params.socialIcons]]
icon = "fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/izewfktvy533zjmn/"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/taichi-soma"



[menue]
    [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"

    [[menu.main]]
    name = "Posts"
    identifier = "posts"
    weight = 200
    url = "/posts/"
