baseURL = "http://techblog.on-going.jp/"
languageCode = "jp"
theme = "anatole"
hasCJKLanguage = true



[params]
title = "on-going's Tech Blog"
author = "techblog.on-going."
description = "GitHub: izewfktvy533zjmn"
profilePicture = "images/profile.jpg"



## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/izewfktvy533zjmn"



[menue]
    [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"

    [[menu.main]]
    name = "Posts"
    identifier = "posts"
    weight = 200
    url = "/posts/"
