baseURL = "https://techblog.on-going.jp/"
languageCode = "jp"
title = "on-going's Tech Blog"
theme = "anatole"
hasCJKLanguage = true
googleAnalytics = "265943608"
DefaultContentLanguage = "ja"


[params]
title = "on-going's Tech Blog"
author = "techblog.on-going."
profilePicture = "images/profile.jpg"
thumbnail = "images/profile.jpg"
twitter = "sosomasox"
commpost = true


## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
    [[params.socialIcons]]
    icon = "fa-github"
    title = "GitHub"
    url = "https://github.com/sosomasox"

    [[params.socialIcons]]
    icon = "fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/sosomasox"

    [[params.socialIcons]]
    icon = "fa-facebook"
    title = "Facebook"
    url = "https://www.facebook.com/profile.php?id=100023692920069"


[menue]
    [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"

    [[menu.main]]
    name = "Posts"
    identifier = "posts"
    weight = 200
    url = "/posts/"
